// SPDX-License-Identifier: MIT

const ARPHRD_NETROM: u16 = 0x0;
const IFT_OTHER: u16 = 0x1;
const IFT_1822: u16 = 0x2;
const IFT_HDH1822: u16 = 0x3;
const IFT_X25DDN: u16 = 0x4;
const IFT_X25: u16 = 0x5;
const IFT_ETHER: u16 = 0x6;
const IFT_ISO88023: u16 = 0x7;
const IFT_ISO88024: u16 = 0x8;
const IFT_ISO88025: u16 = 0x9;
const IFT_ISO88026: u16 = 0xa;
const IFT_STARLAN: u16 = 0xb;
const IFT_P10: u16 = 0xc;
const IFT_P80: u16 = 0xd;
const IFT_HY: u16 = 0xe;
const IFT_FDDI: u16 = 0xf;
const IFT_LAPB: u16 = 0x10;
const IFT_SDLC: u16 = 0x11;
const IFT_T1: u16 = 0x12;
const IFT_CEPT: u16 = 0x13;
const IFT_ISDNBASIC: u16 = 0x14;
const IFT_ISDNPRIMARY: u16 = 0x15;
const IFT_PTPSERIAL: u16 = 0x16;
const IFT_PPP: u16 = 0x17;
const IFT_LOOP: u16 = 0x18;
const IFT_EON: u16 = 0x19;
const IFT_XETHER: u16 = 0x1a;
const IFT_NSIP: u16 = 0x1b;
const IFT_SLIP: u16 = 0x1c;
const IFT_ULTRA: u16 = 0x1d;
const IFT_DS3: u16 = 0x1e;
const IFT_SIP: u16 = 0x1f;
const IFT_FRELAY: u16 = 0x20;
const IFT_RS232: u16 = 0x21;
const IFT_PARA: u16 = 0x22;
const IFT_ARCNET: u16 = 0x23;
const IFT_ARCNETPLUS: u16 = 0x24;
const IFT_ATM: u16 = 0x25;
const IFT_MIOX25: u16 = 0x26;
const IFT_SONET: u16 = 0x27;
const IFT_X25PLE: u16 = 0x28;
const IFT_ISO88022LLC: u16 = 0x29;
const IFT_LOCALTALK: u16 = 0x2a;
const IFT_SMDSDXI: u16 = 0x2b;
const IFT_FRELAYDCE: u16 = 0x2c;
const IFT_V35: u16 = 0x2d;
const IFT_HSSI: u16 = 0x2e;
const IFT_HIPPI: u16 = 0x2f;
const IFT_MODEM: u16 = 0x30;
const IFT_AAL5: u16 = 0x31;
const IFT_SONETPATH: u16 = 0x32;
const IFT_SONETVT: u16 = 0x33;
const IFT_SMDSICIP: u16 = 0x34;
const IFT_PROPVIRTUAL: u16 = 0x35;
const IFT_PROPMUX: u16 = 0x36;
const IFT_IEEE80212: u16 = 0x37;
const IFT_FIBRECHANNEL: u16 = 0x38;
const IFT_HIPPIINTERFACE: u16 = 0x39;
const IFT_FRAMERELAYINTERCONNECT: u16 = 0x3a;
const IFT_AFLANE8023: u16 = 0x3b;
const IFT_AFLANE8025: u16 = 0x3c;
const IFT_CCTEMUL: u16 = 0x3d;
const IFT_FASTETHER: u16 = 0x3e;
const IFT_ISDN: u16 = 0x3f;
const IFT_V11: u16 = 0x40;
const IFT_V36: u16 = 0x41;
const IFT_G703AT64K: u16 = 0x42;
const IFT_G703AT2MB: u16 = 0x43;
const IFT_QLLC: u16 = 0x44;
const IFT_FASTETHERFX: u16 = 0x45;
const IFT_CHANNEL: u16 = 0x46;
const IFT_IEEE80211: u16 = 0x47;
const IFT_IBM370PARCHAN: u16 = 0x48;
const IFT_ESCON: u16 = 0x49;
const IFT_DLSW: u16 = 0x4a;
const IFT_ISDNS: u16 = 0x4b;
const IFT_ISDNU: u16 = 0x4c;
const IFT_LAPD: u16 = 0x4d;
const IFT_IPSWITCH: u16 = 0x4e;
const IFT_RSRB: u16 = 0x4f;
const IFT_ATMLOGICAL: u16 = 0x50;
const IFT_DS0: u16 = 0x51;
const IFT_DS0BUNDLE: u16 = 0x52;
const IFT_BSC: u16 = 0x53;
const IFT_ASYNC: u16 = 0x54;
const IFT_CNR: u16 = 0x55;
const IFT_ISO88025DTR: u16 = 0x56;
const IFT_EPLRS: u16 = 0x57;
const IFT_ARAP: u16 = 0x58;
const IFT_PROPCNLS: u16 = 0x59;
const IFT_HOSTPAD: u16 = 0x5a;
const IFT_TERMPAD: u16 = 0x5b;
const IFT_FRAMERELAYMPI: u16 = 0x5c;
const IFT_X213: u16 = 0x5d;
const IFT_ADSL: u16 = 0x5e;
const IFT_RADSL: u16 = 0x5f;
const IFT_SDSL: u16 = 0x60;
const IFT_VDSL: u16 = 0x61;
const IFT_ISO88025CRFPINT: u16 = 0x62;
const IFT_MYRINET: u16 = 0x63;
const IFT_VOICEEM: u16 = 0x64;
const IFT_VOICEFXO: u16 = 0x65;
const IFT_VOICEFXS: u16 = 0x66;
const IFT_VOICEENCAP: u16 = 0x67;
const IFT_VOICEOVERIP: u16 = 0x68;
const IFT_ATMDXI: u16 = 0x69;
const IFT_ATMFUNI: u16 = 0x6a;
const IFT_ATMIMA: u16 = 0x6b;
const IFT_PPPMULTILINKBUNDLE: u16 = 0x6c;
const IFT_IPOVERCDLC: u16 = 0x6d;
const IFT_IPOVERCLAW: u16 = 0x6e;
const IFT_STACKTOSTACK: u16 = 0x6f;
const IFT_VIRTUALIPADDRESS: u16 = 0x70;
const IFT_MPC: u16 = 0x71;
const IFT_IPOVERATM: u16 = 0x72;
const IFT_ISO88025FIBER: u16 = 0x73;
const IFT_TDLC: u16 = 0x74;
const IFT_GIGABITETHERNET: u16 = 0x75;
const IFT_HDLC: u16 = 0x76;
const IFT_LAPF: u16 = 0x77;
const IFT_V37: u16 = 0x78;
const IFT_X25MLP: u16 = 0x79;
const IFT_X25HUNTGROUP: u16 = 0x7a;
const IFT_TRANSPHDLC: u16 = 0x7b;
const IFT_INTERLEAVE: u16 = 0x7c;
const IFT_FAST: u16 = 0x7d;
const IFT_IP: u16 = 0x7e;
const IFT_DOCSCABLEMACLAYER: u16 = 0x7f;
const IFT_DOCSCABLEDOWNSTREAM: u16 = 0x80;
const IFT_DOCSCABLEUPSTREAM: u16 = 0x81;
const IFT_A12MPPSWITCH: u16 = 0x82;
const IFT_TUNNEL: u16 = 0x83;
const IFT_COFFEE: u16 = 0x84;
const IFT_CES: u16 = 0x85;
const IFT_ATMSUBINTERFACE: u16 = 0x86;
const IFT_L2VLAN: u16 = 0x87;
const IFT_L3IPVLAN: u16 = 0x88;
const IFT_L3IPXVLAN: u16 = 0x89;
const IFT_DIGITALPOWERLINE: u16 = 0x8a;
const IFT_MEDIAMAILOVERIP: u16 = 0x8b;
const IFT_DTM: u16 = 0x8c;
const IFT_DCN: u16 = 0x8d;
const IFT_IPFORWARD: u16 = 0x8e;
const IFT_MSDSL: u16 = 0x8f;
const IFT_IEEE1394: u16 = 0x90;
const IFT_IFGSN: u16 = 0x91;
const IFT_DVBRCCMACLAYER: u16 = 0x92;
const IFT_DVBRCCDOWNSTREAM: u16 = 0x93;
const IFT_DVBRCCUPSTREAM: u16 = 0x94;
const IFT_ATMVIRTUAL: u16 = 0x95;
const IFT_MPLSTUNNEL: u16 = 0x96;
const IFT_SRP: u16 = 0x97;
const IFT_VOICEOVERATM: u16 = 0x98;
const IFT_VOICEOVERFRAMERELAY: u16 = 0x99;
const IFT_IDSL: u16 = 0x9a;
const IFT_COMPOSITELINK: u16 = 0x9b;
const IFT_SS7SIGLINK: u16 = 0x9c;
const IFT_PROPWIRELESSP2P: u16 = 0x9d;
const IFT_FRFORWARD: u16 = 0x9e;
const IFT_RFC1483: u16 = 0x9f;
const IFT_USB: u16 = 0xa0;
const IFT_IEEE8023ADLAG: u16 = 0xa1;
const IFT_BGPPOLICYACCOUNTING: u16 = 0xa2;
const IFT_FRF16MFRBUNDLE: u16 = 0xa3;
const IFT_H323GATEKEEPER: u16 = 0xa4;
const IFT_H323PROXY: u16 = 0xa5;
const IFT_MPLS: u16 = 0xa6;
const IFT_MFSIGLINK: u16 = 0xa7;
const IFT_HDSL2: u16 = 0xa8;
const IFT_SHDSL: u16 = 0xa9;
const IFT_DS1FDL: u16 = 0xaa;
const IFT_POS: u16 = 0xab;
const IFT_DVBASILN: u16 = 0xac;
const IFT_DVBASIOUT: u16 = 0xad;
const IFT_PLC: u16 = 0xae;
const IFT_NFAS: u16 = 0xaf;
const IFT_TR008: u16 = 0xb0;
const IFT_GR303RDT: u16 = 0xb1;
const IFT_GR303IDT: u16 = 0xb2;
const IFT_ISUP: u16 = 0xb3;
const IFT_PROPDOCSWIRELESSMACLAYER: u16 = 0xb4;
const IFT_PROPDOCSWIRELESSDOWNSTREAM: u16 = 0xb5;
const IFT_PROPDOCSWIRELESSUPSTREAM: u16 = 0xb6;
const IFT_HIPERLAN2: u16 = 0xb7;
const IFT_PROPBWAP2MP: u16 = 0xb8;
const IFT_SONETOVERHEADCHANNEL: u16 = 0xb9;
const IFT_DIGITALWRAPPEROVERHEADCHANNEL: u16 = 0xba;
const IFT_AAL2: u16 = 0xbb;
const IFT_RADIOMAC: u16 = 0xbc;
const IFT_ATMRADIO: u16 = 0xbd;
const IFT_IMT: u16 = 0xbe;
const IFT_MVL: u16 = 0xbf;
const IFT_REACHDSL: u16 = 0xc0;
const IFT_FRDLCIENDPT: u16 = 0xc1;
const IFT_ATMVCIENDPT: u16 = 0xc2;
const IFT_OPTICALCHANNEL: u16 = 0xc3;
const IFT_OPTICALTRANSPORT: u16 = 0xc4;
const IFT_INFINIBAND: u16 = 0xc7;
const IFT_INFINIBANDLAG: u16 = 0xc8;
const IFT_BRIDGE: u16 = 0xd1;
const IFT_STF: u16 = 0xd7;
const IFT_GIF: u16 = 0xf0;
const IFT_PVC: u16 = 0xf1;
const IFT_ENC: u16 = 0xf4;
const IFT_PFLOG: u16 = 0xf6;
const IFT_PFSYNC: u16 = 0xf7;
const IFT_WIREGUARD: u16 = 0xf8;
const IFT_MBIM: u16 = 0xf9;

#[derive(Debug, PartialEq, Eq, Clone, Copy, Default)]
#[non_exhaustive]
#[repr(u16)]
// Since this list seldom changes, we do not add `Other(u16)` for unknown data.
// For unknown value, we log a warning message
pub enum LinkLayerType {
    #[default]
    Netrom = ARPHRD_NETROM,
    Other = IFT_OTHER,
    Ift1822 = IFT_1822,
    Hdh1822 = IFT_HDH1822,
    X25Ddn = IFT_X25DDN,
    X25 = IFT_X25,
    Ether = IFT_ETHER,
    Iso88023 = IFT_ISO88023,
    Iso88024 = IFT_ISO88024,
    Iso88025 = IFT_ISO88025,
    Iso88026 = IFT_ISO88026,
    Starlan = IFT_STARLAN,
    P10 = IFT_P10,
    P80 = IFT_P80,
    Hy = IFT_HY,
    Fddi = IFT_FDDI,
    Lapb = IFT_LAPB,
    Sdlc = IFT_SDLC,
    T1 = IFT_T1,
    Cept = IFT_CEPT,
    Isdnbasic = IFT_ISDNBASIC,
    Isdnprimary = IFT_ISDNPRIMARY,
    Ptptserial = IFT_PTPSERIAL,
    Ppp = IFT_PPP,
    Loop = IFT_LOOP,
    Eon = IFT_EON,
    Xether = IFT_XETHER,
    Nsip = IFT_NSIP,
    Slip = IFT_SLIP,
    Ultra = IFT_ULTRA,
    Ds3 = IFT_DS3,
    Sip = IFT_SIP,
    Frelay = IFT_FRELAY,
    Rs232 = IFT_RS232,
    Para = IFT_PARA,
    Arcnet = IFT_ARCNET,
    Arcnetplus = IFT_ARCNETPLUS,
    Atm = IFT_ATM,
    Miox25 = IFT_MIOX25,
    Sonet = IFT_SONET,
    X25ple = IFT_X25PLE,
    Iso88022llc = IFT_ISO88022LLC,
    Localtalk = IFT_LOCALTALK,
    Smdsdxi = IFT_SMDSDXI,
    Frelaydce = IFT_FRELAYDCE,
    V35 = IFT_V35,
    Hssi = IFT_HSSI,
    Hippi = IFT_HIPPI,
    Modem = IFT_MODEM,
    Aal5 = IFT_AAL5,
    Sonetpath = IFT_SONETPATH,
    Sonetvt = IFT_SONETVT,
    Smdsicip = IFT_SMDSICIP,
    Propvirtual = IFT_PROPVIRTUAL,
    Propmux = IFT_PROPMUX,
    Ieee80212 = IFT_IEEE80212,
    Fibrechannel = IFT_FIBRECHANNEL,
    Hippiinterface = IFT_HIPPIINTERFACE,
    Framerelayinterconnect = IFT_FRAMERELAYINTERCONNECT,
    Aflane8023 = IFT_AFLANE8023,
    Aflane8025 = IFT_AFLANE8025,
    Cctemul = IFT_CCTEMUL,
    Fastether = IFT_FASTETHER,
    Isdn = IFT_ISDN,
    V11 = IFT_V11,
    V36 = IFT_V36,
    G703at64k = IFT_G703AT64K,
    G703at2mb = IFT_G703AT2MB,
    Qllc = IFT_QLLC,
    Fastetherfx = IFT_FASTETHERFX,
    Channel = IFT_CHANNEL,
    Ieee80211 = IFT_IEEE80211,
    Ibm370parchan = IFT_IBM370PARCHAN,
    Escon = IFT_ESCON,
    Dlsw = IFT_DLSW,
    Isdns = IFT_ISDNS,
    Isdnu = IFT_ISDNU,
    Lapd = IFT_LAPD,
    Ipswitch = IFT_IPSWITCH,
    Rsrb = IFT_RSRB,
    Atmlogical = IFT_ATMLOGICAL,
    Ds0 = IFT_DS0,
    Ds0bundle = IFT_DS0BUNDLE,
    Bsc = IFT_BSC,
    Async = IFT_ASYNC,
    Cnr = IFT_CNR,
    Iso88025dtr = IFT_ISO88025DTR,
    Eplrs = IFT_EPLRS,
    Arap = IFT_ARAP,
    Propcnls = IFT_PROPCNLS,
    Hostpad = IFT_HOSTPAD,
    Termpad = IFT_TERMPAD,
    Framerelaympi = IFT_FRAMERELAYMPI,
    X213 = IFT_X213,
    Adsl = IFT_ADSL,
    Radsl = IFT_RADSL,
    Sdsl = IFT_SDSL,
    Vdsl = IFT_VDSL,
    Iso88025crfpint = IFT_ISO88025CRFPINT,
    Myrinet = IFT_MYRINET,
    Voiceem = IFT_VOICEEM,
    Voicefxo = IFT_VOICEFXO,
    Voicefxs = IFT_VOICEFXS,
    Voiceencap = IFT_VOICEENCAP,
    Voiceoverip = IFT_VOICEOVERIP,
    Atmdxi = IFT_ATMDXI,
    Atmfuni = IFT_ATMFUNI,
    Atmima = IFT_ATMIMA,
    Pppmultilinkbundle = IFT_PPPMULTILINKBUNDLE,
    Ipovercdlc = IFT_IPOVERCDLC,
    Ipoverclaw = IFT_IPOVERCLAW,
    Stacktostack = IFT_STACKTOSTACK,
    Virtualipaddress = IFT_VIRTUALIPADDRESS,
    Mpc = IFT_MPC,
    Ipoveratm = IFT_IPOVERATM,
    Iso88025fiber = IFT_ISO88025FIBER,
    Tdlc = IFT_TDLC,
    Gigabitethernet = IFT_GIGABITETHERNET,
    Hdlc = IFT_HDLC,
    Lapf = IFT_LAPF,
    V37 = IFT_V37,
    X25mlp = IFT_X25MLP,
    X25huntgroup = IFT_X25HUNTGROUP,
    Transphdlc = IFT_TRANSPHDLC,
    Interleave = IFT_INTERLEAVE,
    Fast = IFT_FAST,
    Ip = IFT_IP,
    Docscablemaclayer = IFT_DOCSCABLEMACLAYER,
    Docscabledownstream = IFT_DOCSCABLEDOWNSTREAM,
    Docscableupstream = IFT_DOCSCABLEUPSTREAM,
    A12mppswitch = IFT_A12MPPSWITCH,
    Tunnel = IFT_TUNNEL,
    Coffee = IFT_COFFEE,
    Ces = IFT_CES,
    Atmsubinterface = IFT_ATMSUBINTERFACE,
    L2vlan = IFT_L2VLAN,
    L3ipvlan = IFT_L3IPVLAN,
    L3ipxvlan = IFT_L3IPXVLAN,
    Digitalpowerline = IFT_DIGITALPOWERLINE,
    Mediamailoverip = IFT_MEDIAMAILOVERIP,
    Dtm = IFT_DTM,
    Dcn = IFT_DCN,
    Ipforward = IFT_IPFORWARD,
    Msdsl = IFT_MSDSL,
    Ieee1394 = IFT_IEEE1394,
    Ifgsn = IFT_IFGSN,
    Dvbrccmaclayer = IFT_DVBRCCMACLAYER,
    Dvbrccdownstream = IFT_DVBRCCDOWNSTREAM,
    Dvbrccupstream = IFT_DVBRCCUPSTREAM,
    Atmvirtual = IFT_ATMVIRTUAL,
    Mplstunnel = IFT_MPLSTUNNEL,
    Srp = IFT_SRP,
    Voiceoveratm = IFT_VOICEOVERATM,
    Voiceoverframerelay = IFT_VOICEOVERFRAMERELAY,
    Idsl = IFT_IDSL,
    Compositelink = IFT_COMPOSITELINK,
    Ss7siglink = IFT_SS7SIGLINK,
    Propwirelessp2p = IFT_PROPWIRELESSP2P,
    Frforward = IFT_FRFORWARD,
    Rfc1483 = IFT_RFC1483,
    Usb = IFT_USB,
    Ieee8023adlag = IFT_IEEE8023ADLAG,
    Bgppolicyaccounting = IFT_BGPPOLICYACCOUNTING,
    Frf16mfrbundle = IFT_FRF16MFRBUNDLE,
    H323gatekeeper = IFT_H323GATEKEEPER,
    H323proxy = IFT_H323PROXY,
    Mpls = IFT_MPLS,
    Mfsiglink = IFT_MFSIGLINK,
    Hdsl2 = IFT_HDSL2,
    Shdsl = IFT_SHDSL,
    Ds1fdl = IFT_DS1FDL,
    Pos = IFT_POS,
    Dvbasiln = IFT_DVBASILN,
    Dvbasioout = IFT_DVBASIOUT,
    Plc = IFT_PLC,
    Nfas = IFT_NFAS,
    Tr008 = IFT_TR008,
    Gr303rdt = IFT_GR303RDT,
    Gr303idt = IFT_GR303IDT,
    Isup = IFT_ISUP,
    Propdocswirelessmaclayer = IFT_PROPDOCSWIRELESSMACLAYER,
    Propdocswirelessdownstream = IFT_PROPDOCSWIRELESSDOWNSTREAM,
    Propdocswirelessupstream = IFT_PROPDOCSWIRELESSUPSTREAM,
    Hiperlan2 = IFT_HIPERLAN2,
    Propbwap2mp = IFT_PROPBWAP2MP,
    Sonetoverheadchannel = IFT_SONETOVERHEADCHANNEL,
    Digitalwrapperoverheadchannel = IFT_DIGITALWRAPPEROVERHEADCHANNEL,
    Aal2 = IFT_AAL2,
    Radiomac = IFT_RADIOMAC,
    Atmradio = IFT_ATMRADIO,
    Imt = IFT_IMT,
    Mvl = IFT_MVL,
    Reachdsl = IFT_REACHDSL,
    Frdlciendpt = IFT_FRDLCIENDPT,
    Atmvciendpt = IFT_ATMVCIENDPT,
    Opticalchannel = IFT_OPTICALCHANNEL,
    Opticaltransport = IFT_OPTICALTRANSPORT,
    Infiniband = IFT_INFINIBAND,
    Infinibandlag = IFT_INFINIBANDLAG,
    Bridge = IFT_BRIDGE,
    Stf = IFT_STF,
    Gif = IFT_GIF,
    Pvc = IFT_PVC,
    Enc = IFT_ENC,
    Pflog = IFT_PFLOG,
    Pfsync = IFT_PFSYNC,
    Wireguard = IFT_WIREGUARD,
    Mbim = IFT_MBIM,
}

impl From<u16> for LinkLayerType {
    fn from(value: u16) -> Self {
        match value {
            ARPHRD_NETROM => LinkLayerType::Netrom,
            IFT_1822 => LinkLayerType::Ift1822,
            IFT_HDH1822 => LinkLayerType::Hdh1822,
            IFT_X25DDN => LinkLayerType::X25Ddn,
            IFT_X25 => LinkLayerType::X25,
            IFT_ETHER => LinkLayerType::Ether,
            IFT_ISO88023 => LinkLayerType::Iso88023,
            IFT_ISO88024 => LinkLayerType::Iso88024,
            IFT_ISO88025 => LinkLayerType::Iso88025,
            IFT_ISO88026 => LinkLayerType::Iso88026,
            IFT_STARLAN => LinkLayerType::Starlan,
            IFT_P10 => LinkLayerType::P10,
            IFT_P80 => LinkLayerType::P80,
            IFT_HY => LinkLayerType::Hy,
            IFT_FDDI => LinkLayerType::Fddi,
            IFT_LAPB => LinkLayerType::Lapb,
            IFT_SDLC => LinkLayerType::Sdlc,
            IFT_T1 => LinkLayerType::T1,
            IFT_CEPT => LinkLayerType::Cept,
            IFT_ISDNBASIC => LinkLayerType::Isdnbasic,
            IFT_ISDNPRIMARY => LinkLayerType::Isdnprimary,
            IFT_PTPSERIAL => LinkLayerType::Ptptserial,
            IFT_PPP => LinkLayerType::Ppp,
            IFT_LOOP => LinkLayerType::Loop,
            IFT_EON => LinkLayerType::Eon,
            IFT_XETHER => LinkLayerType::Xether,
            IFT_NSIP => LinkLayerType::Nsip,
            IFT_SLIP => LinkLayerType::Slip,
            IFT_ULTRA => LinkLayerType::Ultra,
            IFT_DS3 => LinkLayerType::Ds3,
            IFT_SIP => LinkLayerType::Sip,
            IFT_FRELAY => LinkLayerType::Frelay,
            IFT_RS232 => LinkLayerType::Rs232,
            IFT_PARA => LinkLayerType::Para,
            IFT_ARCNET => LinkLayerType::Arcnet,
            IFT_ARCNETPLUS => LinkLayerType::Arcnetplus,
            IFT_ATM => LinkLayerType::Atm,
            IFT_MIOX25 => LinkLayerType::Miox25,
            IFT_SONET => LinkLayerType::Sonet,
            IFT_X25PLE => LinkLayerType::X25ple,
            IFT_ISO88022LLC => LinkLayerType::Iso88022llc,
            IFT_LOCALTALK => LinkLayerType::Localtalk,
            IFT_SMDSDXI => LinkLayerType::Smdsdxi,
            IFT_FRELAYDCE => LinkLayerType::Frelaydce,
            IFT_V35 => LinkLayerType::V35,
            IFT_HSSI => LinkLayerType::Hssi,
            IFT_HIPPI => LinkLayerType::Hippi,
            IFT_MODEM => LinkLayerType::Modem,
            IFT_AAL5 => LinkLayerType::Aal5,
            IFT_SONETPATH => LinkLayerType::Sonetpath,
            IFT_SONETVT => LinkLayerType::Sonetvt,
            IFT_SMDSICIP => LinkLayerType::Smdsicip,
            IFT_PROPVIRTUAL => LinkLayerType::Propvirtual,
            IFT_PROPMUX => LinkLayerType::Propmux,
            IFT_IEEE80212 => LinkLayerType::Ieee80212,
            IFT_FIBRECHANNEL => LinkLayerType::Fibrechannel,
            IFT_HIPPIINTERFACE => LinkLayerType::Hippiinterface,
            IFT_FRAMERELAYINTERCONNECT => LinkLayerType::Framerelayinterconnect,
            IFT_AFLANE8023 => LinkLayerType::Aflane8023,
            IFT_AFLANE8025 => LinkLayerType::Aflane8025,
            IFT_CCTEMUL => LinkLayerType::Cctemul,
            IFT_FASTETHER => LinkLayerType::Fastether,
            IFT_ISDN => LinkLayerType::Isdn,
            IFT_V11 => LinkLayerType::V11,
            IFT_V36 => LinkLayerType::V36,
            IFT_G703AT64K => LinkLayerType::G703at64k,
            IFT_G703AT2MB => LinkLayerType::G703at2mb,
            IFT_QLLC => LinkLayerType::Qllc,
            IFT_FASTETHERFX => LinkLayerType::Fastetherfx,
            IFT_CHANNEL => LinkLayerType::Channel,
            IFT_IEEE80211 => LinkLayerType::Ieee80211,
            IFT_IBM370PARCHAN => LinkLayerType::Ibm370parchan,
            IFT_ESCON => LinkLayerType::Escon,
            IFT_DLSW => LinkLayerType::Dlsw,
            IFT_ISDNS => LinkLayerType::Isdns,
            IFT_ISDNU => LinkLayerType::Isdnu,
            IFT_LAPD => LinkLayerType::Lapd,
            IFT_IPSWITCH => LinkLayerType::Ipswitch,
            IFT_RSRB => LinkLayerType::Rsrb,
            IFT_ATMLOGICAL => LinkLayerType::Atmlogical,
            IFT_DS0 => LinkLayerType::Ds0,
            IFT_DS0BUNDLE => LinkLayerType::Ds0bundle,
            IFT_BSC => LinkLayerType::Bsc,
            IFT_ASYNC => LinkLayerType::Async,
            IFT_CNR => LinkLayerType::Cnr,
            IFT_ISO88025DTR => LinkLayerType::Iso88025dtr,
            IFT_EPLRS => LinkLayerType::Eplrs,
            IFT_ARAP => LinkLayerType::Arap,
            IFT_PROPCNLS => LinkLayerType::Propcnls,
            IFT_HOSTPAD => LinkLayerType::Hostpad,
            IFT_TERMPAD => LinkLayerType::Termpad,
            IFT_FRAMERELAYMPI => LinkLayerType::Framerelaympi,
            IFT_X213 => LinkLayerType::X213,
            IFT_ADSL => LinkLayerType::Adsl,
            IFT_RADSL => LinkLayerType::Radsl,
            IFT_SDSL => LinkLayerType::Sdsl,
            IFT_VDSL => LinkLayerType::Vdsl,
            IFT_ISO88025CRFPINT => LinkLayerType::Iso88025crfpint,
            IFT_MYRINET => LinkLayerType::Myrinet,
            IFT_VOICEEM => LinkLayerType::Voiceem,
            IFT_VOICEFXO => LinkLayerType::Voicefxo,
            IFT_VOICEFXS => LinkLayerType::Voicefxs,
            IFT_VOICEENCAP => LinkLayerType::Voiceencap,
            IFT_VOICEOVERIP => LinkLayerType::Voiceoverip,
            IFT_ATMDXI => LinkLayerType::Atmdxi,
            IFT_ATMFUNI => LinkLayerType::Atmfuni,
            IFT_ATMIMA => LinkLayerType::Atmima,
            IFT_PPPMULTILINKBUNDLE => LinkLayerType::Pppmultilinkbundle,
            IFT_IPOVERCDLC => LinkLayerType::Ipovercdlc,
            IFT_IPOVERCLAW => LinkLayerType::Ipoverclaw,
            IFT_STACKTOSTACK => LinkLayerType::Stacktostack,
            IFT_VIRTUALIPADDRESS => LinkLayerType::Virtualipaddress,
            IFT_MPC => LinkLayerType::Mpc,
            IFT_IPOVERATM => LinkLayerType::Ipoveratm,
            IFT_ISO88025FIBER => LinkLayerType::Iso88025fiber,
            IFT_TDLC => LinkLayerType::Tdlc,
            IFT_GIGABITETHERNET => LinkLayerType::Gigabitethernet,
            IFT_HDLC => LinkLayerType::Hdlc,
            IFT_LAPF => LinkLayerType::Lapf,
            IFT_V37 => LinkLayerType::V37,
            IFT_X25MLP => LinkLayerType::X25mlp,
            IFT_X25HUNTGROUP => LinkLayerType::X25huntgroup,
            IFT_TRANSPHDLC => LinkLayerType::Transphdlc,
            IFT_INTERLEAVE => LinkLayerType::Interleave,
            IFT_FAST => LinkLayerType::Fast,
            IFT_IP => LinkLayerType::Ip,
            IFT_DOCSCABLEMACLAYER => LinkLayerType::Docscablemaclayer,
            IFT_DOCSCABLEDOWNSTREAM => LinkLayerType::Docscabledownstream,
            IFT_DOCSCABLEUPSTREAM => LinkLayerType::Docscableupstream,
            IFT_A12MPPSWITCH => LinkLayerType::A12mppswitch,
            IFT_TUNNEL => LinkLayerType::Tunnel,
            IFT_COFFEE => LinkLayerType::Coffee,
            IFT_CES => LinkLayerType::Ces,
            IFT_ATMSUBINTERFACE => LinkLayerType::Atmsubinterface,
            IFT_L2VLAN => LinkLayerType::L2vlan,
            IFT_L3IPVLAN => LinkLayerType::L3ipvlan,
            IFT_L3IPXVLAN => LinkLayerType::L3ipxvlan,
            IFT_DIGITALPOWERLINE => LinkLayerType::Digitalpowerline,
            IFT_MEDIAMAILOVERIP => LinkLayerType::Mediamailoverip,
            IFT_DTM => LinkLayerType::Dtm,
            IFT_DCN => LinkLayerType::Dcn,
            IFT_IPFORWARD => LinkLayerType::Ipforward,
            IFT_MSDSL => LinkLayerType::Msdsl,
            IFT_IEEE1394 => LinkLayerType::Ieee1394,
            IFT_IFGSN => LinkLayerType::Ifgsn,
            IFT_DVBRCCMACLAYER => LinkLayerType::Dvbrccmaclayer,
            IFT_DVBRCCDOWNSTREAM => LinkLayerType::Dvbrccdownstream,
            IFT_DVBRCCUPSTREAM => LinkLayerType::Dvbrccupstream,
            IFT_ATMVIRTUAL => LinkLayerType::Atmvirtual,
            IFT_MPLSTUNNEL => LinkLayerType::Mplstunnel,
            IFT_SRP => LinkLayerType::Srp,
            IFT_VOICEOVERATM => LinkLayerType::Voiceoveratm,
            IFT_VOICEOVERFRAMERELAY => LinkLayerType::Voiceoverframerelay,
            IFT_IDSL => LinkLayerType::Idsl,
            IFT_COMPOSITELINK => LinkLayerType::Compositelink,
            IFT_SS7SIGLINK => LinkLayerType::Ss7siglink,
            IFT_PROPWIRELESSP2P => LinkLayerType::Propwirelessp2p,
            IFT_FRFORWARD => LinkLayerType::Frforward,
            IFT_RFC1483 => LinkLayerType::Rfc1483,
            IFT_USB => LinkLayerType::Usb,
            IFT_IEEE8023ADLAG => LinkLayerType::Ieee8023adlag,
            IFT_BGPPOLICYACCOUNTING => LinkLayerType::Bgppolicyaccounting,
            IFT_FRF16MFRBUNDLE => LinkLayerType::Frf16mfrbundle,
            IFT_H323GATEKEEPER => LinkLayerType::H323gatekeeper,
            IFT_H323PROXY => LinkLayerType::H323proxy,
            IFT_MPLS => LinkLayerType::Mpls,
            IFT_MFSIGLINK => LinkLayerType::Mfsiglink,
            IFT_HDSL2 => LinkLayerType::Hdsl2,
            IFT_SHDSL => LinkLayerType::Shdsl,
            IFT_DS1FDL => LinkLayerType::Ds1fdl,
            IFT_POS => LinkLayerType::Pos,
            IFT_DVBASILN => LinkLayerType::Dvbasiln,
            IFT_DVBASIOUT => LinkLayerType::Dvbasioout,
            IFT_PLC => LinkLayerType::Plc,
            IFT_NFAS => LinkLayerType::Nfas,
            IFT_TR008 => LinkLayerType::Tr008,
            IFT_GR303RDT => LinkLayerType::Gr303rdt,
            IFT_GR303IDT => LinkLayerType::Gr303idt,
            IFT_ISUP => LinkLayerType::Isup,
            IFT_PROPDOCSWIRELESSMACLAYER => {
                LinkLayerType::Propdocswirelessmaclayer
            }
            IFT_PROPDOCSWIRELESSDOWNSTREAM => {
                LinkLayerType::Propdocswirelessdownstream
            }
            IFT_PROPDOCSWIRELESSUPSTREAM => {
                LinkLayerType::Propdocswirelessupstream
            }
            IFT_HIPERLAN2 => LinkLayerType::Hiperlan2,
            IFT_PROPBWAP2MP => LinkLayerType::Propbwap2mp,
            IFT_SONETOVERHEADCHANNEL => LinkLayerType::Sonetoverheadchannel,
            IFT_DIGITALWRAPPEROVERHEADCHANNEL => {
                LinkLayerType::Digitalwrapperoverheadchannel
            }
            IFT_AAL2 => LinkLayerType::Aal2,
            IFT_RADIOMAC => LinkLayerType::Radiomac,
            IFT_ATMRADIO => LinkLayerType::Atmradio,
            IFT_IMT => LinkLayerType::Imt,
            IFT_MVL => LinkLayerType::Mvl,
            IFT_REACHDSL => LinkLayerType::Reachdsl,
            IFT_FRDLCIENDPT => LinkLayerType::Frdlciendpt,
            IFT_ATMVCIENDPT => LinkLayerType::Atmvciendpt,
            IFT_OPTICALCHANNEL => LinkLayerType::Opticalchannel,
            IFT_OPTICALTRANSPORT => LinkLayerType::Opticaltransport,
            IFT_INFINIBAND => LinkLayerType::Infiniband,
            IFT_INFINIBANDLAG => LinkLayerType::Infinibandlag,
            IFT_BRIDGE => LinkLayerType::Bridge,
            IFT_STF => LinkLayerType::Stf,
            IFT_GIF => LinkLayerType::Gif,
            IFT_PVC => LinkLayerType::Pvc,
            IFT_ENC => LinkLayerType::Enc,
            IFT_PFLOG => LinkLayerType::Pflog,
            IFT_PFSYNC => LinkLayerType::Pfsync,
            IFT_WIREGUARD => LinkLayerType::Wireguard,
            IFT_MBIM => LinkLayerType::Mbim,
            _ => {
                log::warn!(
                    "BUG: Got unknown IFT_XXX {value} for LinkLayerType, \
                     treating it as LinkLayerType::Other"
                );
                LinkLayerType::Other
            }
        }
    }
}

impl std::fmt::Display for LinkLayerType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                LinkLayerType::Netrom => "NETROM",
                LinkLayerType::Other => "OTHER",
                LinkLayerType::Ift1822 => "1822",
                LinkLayerType::Hdh1822 => "HDH1822",
                LinkLayerType::X25Ddn => "X25DDN",
                LinkLayerType::X25 => "X25",
                LinkLayerType::Ether => "ETHERNET",
                LinkLayerType::Iso88023 => "ISO88023",
                LinkLayerType::Iso88024 => "ISO88024",
                LinkLayerType::Iso88025 => "ISO88025",
                LinkLayerType::Iso88026 => "ISO88026",
                LinkLayerType::Starlan => "STARLAN",
                LinkLayerType::P10 => "P10",
                LinkLayerType::P80 => "P80",
                LinkLayerType::Hy => "HY",
                LinkLayerType::Fddi => "FDDI",
                LinkLayerType::Lapb => "LAPB",
                LinkLayerType::Sdlc => "SDLC",
                LinkLayerType::T1 => "T1",
                LinkLayerType::Cept => "CEPT",
                LinkLayerType::Isdnbasic => "ISDN_BASIC",
                LinkLayerType::Isdnprimary => "ISDN_PRIMARY",
                LinkLayerType::Ptptserial => "PTP_SERIAL",
                LinkLayerType::Ppp => "PPP",
                LinkLayerType::Loop => "LOOPBACK",
                LinkLayerType::Eon => "EON",
                LinkLayerType::Xether => "XETHER",
                LinkLayerType::Nsip => "NSIP",
                LinkLayerType::Slip => "SLIP",
                LinkLayerType::Ultra => "ULTRA",
                LinkLayerType::Ds3 => "DS3",
                LinkLayerType::Sip => "SIP",
                LinkLayerType::Frelay => "FRAMERELAY",
                LinkLayerType::Rs232 => "RS232",
                LinkLayerType::Para => "PARALLEL_PORT",
                LinkLayerType::Arcnet => "ARCNET",
                LinkLayerType::Arcnetplus => "ARCNET_PLUS",
                LinkLayerType::Atm => "ATM",
                LinkLayerType::Miox25 => "MIO_X25",
                LinkLayerType::Sonet => "SONET",
                LinkLayerType::X25ple => "X25_PLE",
                LinkLayerType::Iso88022llc => "ISO88022_LLC",
                LinkLayerType::Localtalk => "LOCALTALK",
                LinkLayerType::Smdsdxi => "SMDS_DXI",
                LinkLayerType::Frelaydce => "FRAMERELAY_DCE",
                LinkLayerType::V35 => "V35",
                LinkLayerType::Hssi => "HSSI",
                LinkLayerType::Hippi => "HIPPI",
                LinkLayerType::Modem => "MODEM",
                LinkLayerType::Aal5 => "AAL5",
                LinkLayerType::Sonetpath => "SONET_PATH",
                LinkLayerType::Sonetvt => "SONET_VT",
                LinkLayerType::Smdsicip => "SMDS_ICIP",
                LinkLayerType::Propvirtual => "PROPRIETARY_VIRTUAL",
                LinkLayerType::Propmux => "PROPRIETARY_MUX",
                LinkLayerType::Ieee80212 => "IEEE802.12",
                LinkLayerType::Fibrechannel => "FIBRE_CHANNEL",
                LinkLayerType::Hippiinterface => "HIPPI_INTERFACE",
                LinkLayerType::Framerelayinterconnect =>
                    "FRAMERELAY_INTERCONNECT",
                LinkLayerType::Aflane8023 => "AF_LANE_8023",
                LinkLayerType::Aflane8025 => "AF_LANE_8025",
                LinkLayerType::Cctemul => "CCT_EMUL",
                LinkLayerType::Fastether => "FAST_ETHERNET",
                LinkLayerType::Isdn => "ISDN",
                LinkLayerType::V11 => "V11",
                LinkLayerType::V36 => "V36",
                LinkLayerType::G703at64k => "G703_AT_64K",
                LinkLayerType::G703at2mb => "G703_AT_2MB",
                LinkLayerType::Qllc => "QLLC",
                LinkLayerType::Fastetherfx => "FAST_ETHERNET_FX",
                LinkLayerType::Channel => "CHANNEL",
                LinkLayerType::Ieee80211 => "IEEE802.11",
                LinkLayerType::Ibm370parchan => "IBM_370_PARALLEL_CHANNEL",
                LinkLayerType::Escon => "ESCON",
                LinkLayerType::Dlsw => "DLSW",
                LinkLayerType::Isdns => "ISDN_S",
                LinkLayerType::Isdnu => "ISDN_U",
                LinkLayerType::Lapd => "LAPD",
                LinkLayerType::Ipswitch => "IP_SWITCH",
                LinkLayerType::Rsrb => "RSRB",
                LinkLayerType::Atmlogical => "ATM_LOGICAL",
                LinkLayerType::Ds0 => "DS0",
                LinkLayerType::Ds0bundle => "DS0_BUNDLE",
                LinkLayerType::Bsc => "BSC",
                LinkLayerType::Async => "ASYNC",
                LinkLayerType::Cnr => "CNR",
                LinkLayerType::Iso88025dtr => "ISO88025_DTR",
                LinkLayerType::Eplrs => "EPLRS",
                LinkLayerType::Arap => "ARAP",
                LinkLayerType::Propcnls => "PROPRIETARY_CNLS",
                LinkLayerType::Hostpad => "HOSTPAD",
                LinkLayerType::Termpad => "TERMPAD",
                LinkLayerType::Framerelaympi => "FRAMERELAY_MPI",
                LinkLayerType::X213 => "X213",
                LinkLayerType::Adsl => "ADSL",
                LinkLayerType::Radsl => "RADSL",
                LinkLayerType::Sdsl => "SDSL",
                LinkLayerType::Vdsl => "VDSL",
                LinkLayerType::Iso88025crfpint => "ISO88025_CRFPINT",
                LinkLayerType::Myrinet => "MYRINET",
                LinkLayerType::Voiceem => "VOICE_EM",
                LinkLayerType::Voicefxo => "VOICE_FXO",
                LinkLayerType::Voicefxs => "VOICE_FXS",
                LinkLayerType::Voiceencap => "VOICE_ENCAP",
                LinkLayerType::Voiceoverip => "VOICE_OVER_IP",
                LinkLayerType::Atmdxi => "ATM_DXI",
                LinkLayerType::Atmfuni => "ATM_FUNI",
                LinkLayerType::Atmima => "ATM_IMA",
                LinkLayerType::Pppmultilinkbundle => "PPP_MULTILINK_BUNDLE",
                LinkLayerType::Ipovercdlc => "IP_OVER_CDLC",
                LinkLayerType::Ipoverclaw => "IP_OVER_CLAW",
                LinkLayerType::Stacktostack => "STACK_TO_STACK",
                LinkLayerType::Virtualipaddress => "VIRTUAL_IP_ADDRESS",
                LinkLayerType::Mpc => "MPC",
                LinkLayerType::Ipoveratm => "IP_OVER_ATM",
                LinkLayerType::Iso88025fiber => "ISO88025_FIBER",
                LinkLayerType::Tdlc => "TDLC",
                LinkLayerType::Gigabitethernet => "GIGABIT_ETHERNET",
                LinkLayerType::Hdlc => "HDLC",
                LinkLayerType::Lapf => "LAPF",
                LinkLayerType::V37 => "V37",
                LinkLayerType::X25mlp => "X25_MLP",
                LinkLayerType::X25huntgroup => "X25_HUNT_GROUP",
                LinkLayerType::Transphdlc => "TRANSP_HDL_C",
                LinkLayerType::Interleave => "INTERLEAVE",
                LinkLayerType::Fast => "FAST",
                LinkLayerType::Ip => "IP",
                LinkLayerType::Docscablemaclayer => "DOCS_CABLE_MAC_LAYER",
                LinkLayerType::Docscabledownstream => "DOCS_CABLE_DOWNSTREAM",
                LinkLayerType::Docscableupstream => "DOCS_CABLE_UPSTREAM",
                LinkLayerType::A12mppswitch => "A12MPP_SWITCH",
                LinkLayerType::Tunnel => "TUNNEL",
                LinkLayerType::Coffee => "COFFEE",
                LinkLayerType::Ces => "CES",
                LinkLayerType::Atmsubinterface => "ATM_SUBINTERFACE",
                LinkLayerType::L2vlan => "L2VLAN",
                LinkLayerType::L3ipvlan => "L3IPVLAN",
                LinkLayerType::L3ipxvlan => "L3IPXVLAN",
                LinkLayerType::Digitalpowerline => "DIGITAL_POWERLINE",
                LinkLayerType::Mediamailoverip => "MEDIA_MAIL_OVER_IP",
                LinkLayerType::Dtm => "DTM",
                LinkLayerType::Dcn => "DCN",
                LinkLayerType::Ipforward => "IP_FORWARD",
                LinkLayerType::Msdsl => "MSDSL",
                LinkLayerType::Ieee1394 => "IEEE1394",
                LinkLayerType::Ifgsn => "IFGSN",
                LinkLayerType::Dvbrccmaclayer => "DVB_RCC_MAC_LAYER",
                LinkLayerType::Dvbrccdownstream => "DVB_RCC_DOWNSTREAM",
                LinkLayerType::Dvbrccupstream => "DVB_RCC_UPSTREAM",
                LinkLayerType::Atmvirtual => "ATM_VIRTUAL",
                LinkLayerType::Mplstunnel => "MPLS_TUNNEL",
                LinkLayerType::Srp => "SRP",
                LinkLayerType::Voiceoveratm => "VOICE_OVER_ATM",
                LinkLayerType::Voiceoverframerelay => "VOICE_OVER_FRAMERELAY",
                LinkLayerType::Idsl => "IDSL",
                LinkLayerType::Compositelink => "COMPOSITE_LINK",
                LinkLayerType::Ss7siglink => "SS7_SIG_LINK",
                LinkLayerType::Propwirelessp2p => "PROPRIETARY_WIRELESS_P2P",
                LinkLayerType::Frforward => "FR_FORWARD",
                LinkLayerType::Rfc1483 => "RFC1483",
                LinkLayerType::Usb => "USB",
                LinkLayerType::Ieee8023adlag => "IEEE802.3AD_LAG",
                LinkLayerType::Bgppolicyaccounting => "BGP_POLICY_ACCOUNTING",
                LinkLayerType::Frf16mfrbundle => "FRF.16_MFR_BUNDLE",
                LinkLayerType::H323gatekeeper => "H323_GATEKEEPER",
                LinkLayerType::H323proxy => "H323_PROXY",
                LinkLayerType::Mpls => "MPLS",
                LinkLayerType::Mfsiglink => "MF_SIG_LINK",
                LinkLayerType::Hdsl2 => "HDSL2",
                LinkLayerType::Shdsl => "SHDSL",
                LinkLayerType::Ds1fdl => "DS1_FDL",
                LinkLayerType::Pos => "POS",
                LinkLayerType::Dvbasiln => "DVB_ASI_LN",
                LinkLayerType::Dvbasioout => "DVB_ASI_OUT",
                LinkLayerType::Plc => "PLC",
                LinkLayerType::Nfas => "NFAS",
                LinkLayerType::Tr008 => "TR-008",
                LinkLayerType::Gr303rdt => "GR-303_RDT",
                LinkLayerType::Gr303idt => "GR-303_IDT",
                LinkLayerType::Isup => "ISUP",
                LinkLayerType::Propdocswirelessmaclayer =>
                    "PROPRIETARY_DOCS_WIRELESS_MAC_LAYER",
                LinkLayerType::Propdocswirelessdownstream =>
                    "PROPRIETARY_DOCS_WIRELESS_DOWNSTREAM",
                LinkLayerType::Propdocswirelessupstream =>
                    "PROPRIETARY_DOCS_WIRELESS_UPSTREAM",
                LinkLayerType::Hiperlan2 => "HIPERLAN2",
                LinkLayerType::Propbwap2mp => "PROPRIETARY_BWAP_2MP",
                LinkLayerType::Sonetoverheadchannel => "SONET_OVERHEAD_CHANNEL",
                LinkLayerType::Digitalwrapperoverheadchannel =>
                    "DIGITAL_WRAPPER_OVERHEAD_CHANNEL",
                LinkLayerType::Aal2 => "AAL2",
                LinkLayerType::Radiomac => "RADIO_MAC",
                LinkLayerType::Atmradio => "ATM_RADIO",
                LinkLayerType::Imt => "IMT",
                LinkLayerType::Mvl => "MVL",
                LinkLayerType::Reachdsl => "REACHDSL",
                LinkLayerType::Frdlciendpt => "FR_DLCI_ENDPT",
                LinkLayerType::Atmvciendpt => "ATM_VCI_ENDPT",
                LinkLayerType::Opticalchannel => "OPTICAL_CHANNEL",
                LinkLayerType::Opticaltransport => "OPTICAL_TRANSPORT",
                LinkLayerType::Infiniband => "INFINIBAND",
                LinkLayerType::Infinibandlag => "INFINIBAND_LAG",
                LinkLayerType::Bridge => "BRIDGE",
                LinkLayerType::Stf => "STF",
                LinkLayerType::Gif => "GIF",
                LinkLayerType::Pvc => "PVC",
                LinkLayerType::Enc => "ENC",
                LinkLayerType::Pflog => "PFLOG",
                LinkLayerType::Pfsync => "PFSYNC",
                LinkLayerType::Wireguard => "WIREGUARD",
                LinkLayerType::Mbim => "MBIM",
            }
        )
    }
}
