// SPDX-License-Identifier: MIT

/* automatically generated by rust-bindgen 0.71.1 */

#![allow(
    dead_code,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals
)]

pub const AF_NETLINK: u32 = 38;
pub const SOL_NETLINK: u32 = 270;
pub const NETLINK_GET_STRICT_CHK: u32 = 12;
pub const NETLINK_MSG_INFO: u32 = 257;
pub const NETLINK_ROUTE: u32 = 0;
pub const IFF_UP: u32 = 1;
pub const RTMGRP_LINK: u32 = 1;
pub const RTMGRP_IPV4_IFADDR: u32 = 16;
pub const RTMGRP_IPV4_ROUTE: u32 = 64;
pub const RTMGRP_IPV6_IFADDR: u32 = 256;
pub const RTMGRP_IPV6_ROUTE: u32 = 1024;
pub const SIOCSIFFLAGS: u32 = 2149607696;
pub const SIOCGIFFLAGS: u32 = 3223349521;
pub const SIOCIFCREATE2: u32 = 3223349628;
pub const IEEE80211_IOC_SSID: u32 = 1;
pub const IEEE80211_IOC_NUMSSIDS: u32 = 2;
pub const IEEE80211_IOC_WEP: u32 = 3;
pub const IEEE80211_IOC_WEPKEY: u32 = 4;
pub const IEEE80211_IOC_NUMWEPKEYS: u32 = 5;
pub const IEEE80211_IOC_WEPTXKEY: u32 = 6;
pub const IEEE80211_IOC_AUTHMODE: u32 = 7;
pub const IEEE80211_IOC_STATIONNAME: u32 = 8;
pub const IEEE80211_IOC_CHANNEL: u32 = 9;
pub const IEEE80211_IOC_POWERSAVE: u32 = 10;
pub const IEEE80211_IOC_POWERSAVESLEEP: u32 = 11;
pub const IEEE80211_IOC_RTSTHRESHOLD: u32 = 12;
pub const IEEE80211_IOC_PROTMODE: u32 = 13;
pub const IEEE80211_IOC_TXPOWER: u32 = 14;
pub const IEEE80211_IOC_BSSID: u32 = 15;
pub const IEEE80211_IOC_ROAMING: u32 = 16;
pub const IEEE80211_IOC_PRIVACY: u32 = 17;
pub const IEEE80211_IOC_DROPUNENCRYPTED: u32 = 18;
pub const IEEE80211_IOC_WPAKEY: u32 = 19;
pub const IEEE80211_IOC_DELKEY: u32 = 20;
pub const IEEE80211_IOC_MLME: u32 = 21;
pub const IEEE80211_IOC_COUNTERMEASURES: u32 = 25;
pub const IEEE80211_IOC_WPA: u32 = 26;
pub const IEEE80211_IOC_CHANLIST: u32 = 27;
pub const IEEE80211_IOC_WME: u32 = 28;
pub const IEEE80211_IOC_HIDESSID: u32 = 29;
pub const IEEE80211_IOC_APBRIDGE: u32 = 30;
pub const IEEE80211_IOC_WPAIE: u32 = 39;
pub const IEEE80211_IOC_STA_STATS: u32 = 40;
pub const IEEE80211_IOC_MACCMD: u32 = 41;
pub const IEEE80211_IOC_CHANINFO: u32 = 42;
pub const IEEE80211_IOC_TXPOWMAX: u32 = 43;
pub const IEEE80211_IOC_STA_TXPOW: u32 = 44;
pub const IEEE80211_IOC_WME_CWMIN: u32 = 46;
pub const IEEE80211_IOC_WME_CWMAX: u32 = 47;
pub const IEEE80211_IOC_WME_AIFS: u32 = 48;
pub const IEEE80211_IOC_WME_TXOPLIMIT: u32 = 49;
pub const IEEE80211_IOC_WME_ACM: u32 = 50;
pub const IEEE80211_IOC_WME_ACKPOLICY: u32 = 51;
pub const IEEE80211_IOC_DTIM_PERIOD: u32 = 52;
pub const IEEE80211_IOC_BEACON_INTERVAL: u32 = 53;
pub const IEEE80211_IOC_ADDMAC: u32 = 54;
pub const IEEE80211_IOC_DELMAC: u32 = 55;
pub const IEEE80211_IOC_PUREG: u32 = 56;
pub const IEEE80211_IOC_FF: u32 = 57;
pub const IEEE80211_IOC_TURBOP: u32 = 58;
pub const IEEE80211_IOC_BGSCAN: u32 = 59;
pub const IEEE80211_IOC_BGSCAN_IDLE: u32 = 60;
pub const IEEE80211_IOC_BGSCAN_INTERVAL: u32 = 61;
pub const IEEE80211_IOC_SCANVALID: u32 = 65;
pub const IEEE80211_IOC_FRAGTHRESHOLD: u32 = 73;
pub const IEEE80211_IOC_BURST: u32 = 75;
pub const IEEE80211_IOC_SCAN_RESULTS: u32 = 76;
pub const IEEE80211_IOC_BMISSTHRESHOLD: u32 = 77;
pub const IEEE80211_IOC_STA_INFO: u32 = 78;
pub const IEEE80211_IOC_WPAIE2: u32 = 79;
pub const IEEE80211_IOC_CURCHAN: u32 = 80;
pub const IEEE80211_IOC_SHORTGI: u32 = 81;
pub const IEEE80211_IOC_AMPDU: u32 = 82;
pub const IEEE80211_IOC_AMPDU_LIMIT: u32 = 83;
pub const IEEE80211_IOC_AMPDU_DENSITY: u32 = 84;
pub const IEEE80211_IOC_AMSDU: u32 = 85;
pub const IEEE80211_IOC_AMSDU_LIMIT: u32 = 86;
pub const IEEE80211_IOC_PUREN: u32 = 87;
pub const IEEE80211_IOC_DOTH: u32 = 88;
pub const IEEE80211_IOC_HTCOMPAT: u32 = 92;
pub const IEEE80211_IOC_DWDS: u32 = 93;
pub const IEEE80211_IOC_INACTIVITY: u32 = 94;
pub const IEEE80211_IOC_APPIE: u32 = 95;
pub const IEEE80211_IOC_WPS: u32 = 96;
pub const IEEE80211_IOC_TSN: u32 = 97;
pub const IEEE80211_IOC_DEVCAPS: u32 = 98;
pub const IEEE80211_IOC_CHANSWITCH: u32 = 99;
pub const IEEE80211_IOC_DFS: u32 = 100;
pub const IEEE80211_IOC_DOTD: u32 = 101;
pub const IEEE80211_IOC_HTPROTMODE: u32 = 102;
pub const IEEE80211_IOC_SCAN_REQ: u32 = 103;
pub const IEEE80211_IOC_SCAN_CANCEL: u32 = 104;
pub const IEEE80211_IOC_HTCONF: u32 = 105;
pub const IEEE80211_IOC_REGDOMAIN: u32 = 106;
pub const IEEE80211_IOC_ROAM: u32 = 107;
pub const IEEE80211_IOC_TXPARAMS: u32 = 108;
pub const IEEE80211_IOC_STA_VLAN: u32 = 109;
pub const IEEE80211_IOC_SMPS: u32 = 110;
pub const IEEE80211_IOC_RIFS: u32 = 111;
pub const IEEE80211_IOC_GREENFIELD: u32 = 112;
pub const IEEE80211_IOC_STBC: u32 = 113;
pub const IEEE80211_IOC_LDPC: u32 = 114;
pub const IEEE80211_IOC_UAPSD: u32 = 115;
pub const IEEE80211_IOC_UAPSD_INFO: u32 = 116;
pub const IEEE80211_IOC_VHTCONF: u32 = 130;
pub const IEEE80211_IOC_MESH_ID: u32 = 170;
pub const IEEE80211_IOC_MESH_AP: u32 = 171;
pub const IEEE80211_IOC_MESH_FWRD: u32 = 172;
pub const IEEE80211_IOC_MESH_PROTO: u32 = 173;
pub const IEEE80211_IOC_MESH_TTL: u32 = 174;
pub const IEEE80211_IOC_MESH_RTCMD: u32 = 175;
pub const IEEE80211_IOC_MESH_PR_METRIC: u32 = 176;
pub const IEEE80211_IOC_MESH_PR_PATH: u32 = 177;
pub const IEEE80211_IOC_MESH_PR_SIG: u32 = 178;
pub const IEEE80211_IOC_MESH_PR_CC: u32 = 179;
pub const IEEE80211_IOC_MESH_PR_AUTH: u32 = 180;
pub const IEEE80211_IOC_MESH_GATE: u32 = 181;
pub const IEEE80211_IOC_HWMP_ROOTMODE: u32 = 190;
pub const IEEE80211_IOC_HWMP_MAXHOPS: u32 = 191;
pub const IEEE80211_IOC_HWMP_TTL: u32 = 192;
pub const IEEE80211_IOC_TDMA_SLOT: u32 = 201;
pub const IEEE80211_IOC_TDMA_SLOTCNT: u32 = 202;
pub const IEEE80211_IOC_TDMA_SLOTLEN: u32 = 203;
pub const IEEE80211_IOC_TDMA_BINTERVAL: u32 = 204;
pub const IEEE80211_IOC_QUIET: u32 = 205;
pub const IEEE80211_IOC_QUIET_PERIOD: u32 = 206;
pub const IEEE80211_IOC_QUIET_OFFSET: u32 = 207;
pub const IEEE80211_IOC_QUIET_DUR: u32 = 208;
pub const IEEE80211_IOC_QUIET_COUNT: u32 = 209;
pub const IEEE80211_IOC_IC_NAME: u32 = 210;
pub const IEEE80211_IOC_SCAN_NOPICK: u32 = 1;
pub const IEEE80211_IOC_SCAN_ACTIVE: u32 = 2;
pub const IEEE80211_IOC_SCAN_PICK1ST: u32 = 4;
pub const IEEE80211_IOC_SCAN_BGSCAN: u32 = 8;
pub const IEEE80211_IOC_SCAN_ONCE: u32 = 16;
pub const IEEE80211_IOC_SCAN_NOBCAST: u32 = 32;
pub const IEEE80211_IOC_SCAN_NOJOIN: u32 = 64;
pub const IEEE80211_IOC_SCAN_FLUSH: u32 = 65536;
pub const IEEE80211_IOC_SCAN_CHECK: u32 = 131072;
pub const IEEE80211_IOC_SCAN_DURATION_MIN: u32 = 1;
pub const IEEE80211_IOC_SCAN_DURATION_MAX: u32 = 2147483647;
pub const IEEE80211_IOC_SCAN_FOREVER: u32 = 2147483647;
pub const IEEE80211_IOC_SCAN_MAX_SSID: u32 = 3;
pub const SIOCGIFINFO_IN6: u32 = 3225971052;
pub const SIOCSIFINFO_IN6: u32 = 3225971053;
pub const ND6_IFF_ACCEPT_RTADV: u32 = 2;
pub type __uint8_t = ::core::ffi::c_uchar;
pub type __uint32_t = ::core::ffi::c_uint;
pub type __sa_family_t = __uint8_t;
pub type sa_family_t = __sa_family_t;
pub type u_int8_t = __uint8_t;
pub type u_int32_t = __uint32_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr_nl {
    pub nl_len: u8,
    pub nl_family: sa_family_t,
    pub nl_pad: u16,
    pub nl_pid: u32,
    pub nl_groups: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sockaddr_nl"][::core::mem::size_of::<sockaddr_nl>() - 12usize];
    ["Alignment of sockaddr_nl"]
        [::core::mem::align_of::<sockaddr_nl>() - 4usize];
    ["Offset of field: sockaddr_nl::nl_len"]
        [::core::mem::offset_of!(sockaddr_nl, nl_len) - 0usize];
    ["Offset of field: sockaddr_nl::nl_family"]
        [::core::mem::offset_of!(sockaddr_nl, nl_family) - 1usize];
    ["Offset of field: sockaddr_nl::nl_pad"]
        [::core::mem::offset_of!(sockaddr_nl, nl_pad) - 2usize];
    ["Offset of field: sockaddr_nl::nl_pid"]
        [::core::mem::offset_of!(sockaddr_nl, nl_pid) - 4usize];
    ["Offset of field: sockaddr_nl::nl_groups"]
        [::core::mem::offset_of!(sockaddr_nl, nl_groups) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nlmsghdr {
    pub nlmsg_len: u32,
    pub nlmsg_type: u16,
    pub nlmsg_flags: u16,
    pub nlmsg_seq: u32,
    pub nlmsg_pid: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nlmsghdr"][::core::mem::size_of::<nlmsghdr>() - 16usize];
    ["Alignment of nlmsghdr"][::core::mem::align_of::<nlmsghdr>() - 4usize];
    ["Offset of field: nlmsghdr::nlmsg_len"]
        [::core::mem::offset_of!(nlmsghdr, nlmsg_len) - 0usize];
    ["Offset of field: nlmsghdr::nlmsg_type"]
        [::core::mem::offset_of!(nlmsghdr, nlmsg_type) - 4usize];
    ["Offset of field: nlmsghdr::nlmsg_flags"]
        [::core::mem::offset_of!(nlmsghdr, nlmsg_flags) - 6usize];
    ["Offset of field: nlmsghdr::nlmsg_seq"]
        [::core::mem::offset_of!(nlmsghdr, nlmsg_seq) - 8usize];
    ["Offset of field: nlmsghdr::nlmsg_pid"]
        [::core::mem::offset_of!(nlmsghdr, nlmsg_pid) - 12usize];
};
pub const IEEE80211_M_IBSS: ieee80211_opmode = 0;
pub const IEEE80211_M_STA: ieee80211_opmode = 1;
pub const IEEE80211_M_WDS: ieee80211_opmode = 2;
pub const IEEE80211_M_AHDEMO: ieee80211_opmode = 3;
pub const IEEE80211_M_HOSTAP: ieee80211_opmode = 4;
pub const IEEE80211_M_MONITOR: ieee80211_opmode = 5;
pub const IEEE80211_M_MBSS: ieee80211_opmode = 6;
pub type ieee80211_opmode = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ieee80211_clone_params {
    pub icp_parent: [::core::ffi::c_char; 16usize],
    pub icp_opmode: u16,
    pub icp_flags: u16,
    pub icp_bssid: [u8; 6usize],
    pub icp_macaddr: [u8; 6usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ieee80211_clone_params"]
        [::core::mem::size_of::<ieee80211_clone_params>() - 32usize];
    ["Alignment of ieee80211_clone_params"]
        [::core::mem::align_of::<ieee80211_clone_params>() - 2usize];
    ["Offset of field: ieee80211_clone_params::icp_parent"]
        [::core::mem::offset_of!(ieee80211_clone_params, icp_parent) - 0usize];
    ["Offset of field: ieee80211_clone_params::icp_opmode"]
        [::core::mem::offset_of!(ieee80211_clone_params, icp_opmode) - 16usize];
    ["Offset of field: ieee80211_clone_params::icp_flags"]
        [::core::mem::offset_of!(ieee80211_clone_params, icp_flags) - 18usize];
    ["Offset of field: ieee80211_clone_params::icp_bssid"]
        [::core::mem::offset_of!(ieee80211_clone_params, icp_bssid) - 20usize];
    ["Offset of field: ieee80211_clone_params::icp_macaddr"][::core::mem::offset_of!(
        ieee80211_clone_params,
        icp_macaddr
    ) - 26usize];
};
pub const CTRY_AFGHANISTAN: ISOCountryCode = 4;
pub const CTRY_ALBANIA: ISOCountryCode = 8;
pub const CTRY_ALGERIA: ISOCountryCode = 12;
pub const CTRY_AMERICAN_SAMOA: ISOCountryCode = 16;
pub const CTRY_ANDORRA: ISOCountryCode = 20;
pub const CTRY_ANGOLA: ISOCountryCode = 24;
pub const CTRY_ANGUILLA: ISOCountryCode = 660;
pub const CTRY_ANTARTICA: ISOCountryCode = 10;
pub const CTRY_ANTIGUA: ISOCountryCode = 28;
pub const CTRY_ARGENTINA: ISOCountryCode = 32;
pub const CTRY_ARMENIA: ISOCountryCode = 51;
pub const CTRY_ARUBA: ISOCountryCode = 533;
pub const CTRY_AUSTRALIA: ISOCountryCode = 36;
pub const CTRY_AUSTRIA: ISOCountryCode = 40;
pub const CTRY_AZERBAIJAN: ISOCountryCode = 31;
pub const CTRY_BAHAMAS: ISOCountryCode = 44;
pub const CTRY_BAHRAIN: ISOCountryCode = 48;
pub const CTRY_BANGLADESH: ISOCountryCode = 50;
pub const CTRY_BARBADOS: ISOCountryCode = 52;
pub const CTRY_BELARUS: ISOCountryCode = 112;
pub const CTRY_BELGIUM: ISOCountryCode = 56;
pub const CTRY_BELIZE: ISOCountryCode = 84;
pub const CTRY_BENIN: ISOCountryCode = 204;
pub const CTRY_BERMUDA: ISOCountryCode = 60;
pub const CTRY_BHUTAN: ISOCountryCode = 64;
pub const CTRY_BOLIVIA: ISOCountryCode = 68;
pub const CTRY_BOSNIA_AND_HERZEGOWINA: ISOCountryCode = 70;
pub const CTRY_BOTSWANA: ISOCountryCode = 72;
pub const CTRY_BOUVET_ISLAND: ISOCountryCode = 74;
pub const CTRY_BRAZIL: ISOCountryCode = 76;
pub const CTRY_BRITISH_INDIAN_OCEAN_TERRITORY: ISOCountryCode = 86;
pub const CTRY_BRUNEI_DARUSSALAM: ISOCountryCode = 96;
pub const CTRY_BULGARIA: ISOCountryCode = 100;
pub const CTRY_BURKINA_FASO: ISOCountryCode = 854;
pub const CTRY_BURUNDI: ISOCountryCode = 108;
pub const CTRY_CAMBODIA: ISOCountryCode = 116;
pub const CTRY_CAMEROON: ISOCountryCode = 120;
pub const CTRY_CANADA: ISOCountryCode = 124;
pub const CTRY_CAPE_VERDE: ISOCountryCode = 132;
pub const CTRY_CAYMAN_ISLANDS: ISOCountryCode = 136;
pub const CTRY_CENTRAL_AFRICAN_REPUBLIC: ISOCountryCode = 140;
pub const CTRY_CHAD: ISOCountryCode = 148;
pub const CTRY_CHILE: ISOCountryCode = 152;
pub const CTRY_CHINA: ISOCountryCode = 156;
pub const CTRY_CHRISTMAS_ISLAND: ISOCountryCode = 162;
pub const CTRY_COCOS_ISLANDS: ISOCountryCode = 166;
pub const CTRY_COLOMBIA: ISOCountryCode = 170;
pub const CTRY_COMOROS: ISOCountryCode = 174;
pub const CTRY_CONGO: ISOCountryCode = 178;
pub const CTRY_COOK_ISLANDS: ISOCountryCode = 184;
pub const CTRY_COSTA_RICA: ISOCountryCode = 188;
pub const CTRY_COTE_DIVOIRE: ISOCountryCode = 384;
pub const CTRY_CROATIA: ISOCountryCode = 191;
pub const CTRY_CYPRUS: ISOCountryCode = 196;
pub const CTRY_CZECH: ISOCountryCode = 203;
pub const CTRY_DENMARK: ISOCountryCode = 208;
pub const CTRY_DJIBOUTI: ISOCountryCode = 262;
pub const CTRY_DOMINICA: ISOCountryCode = 212;
pub const CTRY_DOMINICAN_REPUBLIC: ISOCountryCode = 214;
pub const CTRY_EAST_TIMOR: ISOCountryCode = 626;
pub const CTRY_ECUADOR: ISOCountryCode = 218;
pub const CTRY_EGYPT: ISOCountryCode = 818;
pub const CTRY_EL_SALVADOR: ISOCountryCode = 222;
pub const CTRY_EQUATORIAL_GUINEA: ISOCountryCode = 226;
pub const CTRY_ERITREA: ISOCountryCode = 232;
pub const CTRY_ESTONIA: ISOCountryCode = 233;
pub const CTRY_ETHIOPIA: ISOCountryCode = 210;
pub const CTRY_FALKLAND_ISLANDS: ISOCountryCode = 238;
pub const CTRY_FAEROE_ISLANDS: ISOCountryCode = 234;
pub const CTRY_FIJI: ISOCountryCode = 242;
pub const CTRY_FINLAND: ISOCountryCode = 246;
pub const CTRY_FRANCE: ISOCountryCode = 250;
pub const CTRY_FRANCE2: ISOCountryCode = 255;
pub const CTRY_FRENCH_GUIANA: ISOCountryCode = 254;
pub const CTRY_FRENCH_POLYNESIA: ISOCountryCode = 258;
pub const CTRY_FRENCH_SOUTHERN_TERRITORIES: ISOCountryCode = 260;
pub const CTRY_GABON: ISOCountryCode = 266;
pub const CTRY_GAMBIA: ISOCountryCode = 270;
pub const CTRY_GEORGIA: ISOCountryCode = 268;
pub const CTRY_GERMANY: ISOCountryCode = 276;
pub const CTRY_GHANA: ISOCountryCode = 288;
pub const CTRY_GIBRALTAR: ISOCountryCode = 292;
pub const CTRY_GREECE: ISOCountryCode = 300;
pub const CTRY_GREENLAND: ISOCountryCode = 304;
pub const CTRY_GRENADA: ISOCountryCode = 308;
pub const CTRY_GUADELOUPE: ISOCountryCode = 312;
pub const CTRY_GUAM: ISOCountryCode = 316;
pub const CTRY_GUATEMALA: ISOCountryCode = 320;
pub const CTRY_GUINEA: ISOCountryCode = 324;
pub const CTRY_GUINEA_BISSAU: ISOCountryCode = 624;
pub const CTRY_GUYANA: ISOCountryCode = 328;
pub const CTRY_HAITI: ISOCountryCode = 332;
pub const CTRY_HONDURAS: ISOCountryCode = 340;
pub const CTRY_HONG_KONG: ISOCountryCode = 344;
pub const CTRY_HUNGARY: ISOCountryCode = 348;
pub const CTRY_ICELAND: ISOCountryCode = 352;
pub const CTRY_INDIA: ISOCountryCode = 356;
pub const CTRY_INDONESIA: ISOCountryCode = 360;
pub const CTRY_IRAN: ISOCountryCode = 364;
pub const CTRY_IRAQ: ISOCountryCode = 368;
pub const CTRY_IRELAND: ISOCountryCode = 372;
pub const CTRY_ISRAEL: ISOCountryCode = 376;
pub const CTRY_ITALY: ISOCountryCode = 380;
pub const CTRY_JAMAICA: ISOCountryCode = 388;
pub const CTRY_JAPAN: ISOCountryCode = 392;
pub const CTRY_JORDAN: ISOCountryCode = 400;
pub const CTRY_KAZAKHSTAN: ISOCountryCode = 398;
pub const CTRY_KENYA: ISOCountryCode = 404;
pub const CTRY_KOREA_NORTH: ISOCountryCode = 408;
pub const CTRY_KOREA_ROC: ISOCountryCode = 410;
pub const CTRY_KOREA_ROC2: ISOCountryCode = 411;
pub const CTRY_KUWAIT: ISOCountryCode = 414;
pub const CTRY_LATVIA: ISOCountryCode = 428;
pub const CTRY_LEBANON: ISOCountryCode = 422;
pub const CTRY_LIBYA: ISOCountryCode = 434;
pub const CTRY_LIECHTENSTEIN: ISOCountryCode = 438;
pub const CTRY_LITHUANIA: ISOCountryCode = 440;
pub const CTRY_LUXEMBOURG: ISOCountryCode = 442;
pub const CTRY_MACAU: ISOCountryCode = 446;
pub const CTRY_MACEDONIA: ISOCountryCode = 807;
pub const CTRY_MALAYSIA: ISOCountryCode = 458;
pub const CTRY_MALTA: ISOCountryCode = 470;
pub const CTRY_MEXICO: ISOCountryCode = 484;
pub const CTRY_MONACO: ISOCountryCode = 492;
pub const CTRY_MOROCCO: ISOCountryCode = 504;
pub const CTRY_NEPAL: ISOCountryCode = 524;
pub const CTRY_NETHERLANDS: ISOCountryCode = 528;
pub const CTRY_NEW_ZEALAND: ISOCountryCode = 554;
pub const CTRY_NICARAGUA: ISOCountryCode = 558;
pub const CTRY_NORWAY: ISOCountryCode = 578;
pub const CTRY_OMAN: ISOCountryCode = 512;
pub const CTRY_PAKISTAN: ISOCountryCode = 586;
pub const CTRY_PANAMA: ISOCountryCode = 591;
pub const CTRY_PARAGUAY: ISOCountryCode = 600;
pub const CTRY_PERU: ISOCountryCode = 604;
pub const CTRY_PHILIPPINES: ISOCountryCode = 608;
pub const CTRY_POLAND: ISOCountryCode = 616;
pub const CTRY_PORTUGAL: ISOCountryCode = 620;
pub const CTRY_PUERTO_RICO: ISOCountryCode = 630;
pub const CTRY_QATAR: ISOCountryCode = 634;
pub const CTRY_ROMANIA: ISOCountryCode = 642;
pub const CTRY_RUSSIA: ISOCountryCode = 643;
pub const CTRY_SAUDI_ARABIA: ISOCountryCode = 682;
pub const CTRY_SINGAPORE: ISOCountryCode = 702;
pub const CTRY_SLOVAKIA: ISOCountryCode = 703;
pub const CTRY_SLOVENIA: ISOCountryCode = 705;
pub const CTRY_SOUTH_AFRICA: ISOCountryCode = 710;
pub const CTRY_SPAIN: ISOCountryCode = 724;
pub const CTRY_SRILANKA: ISOCountryCode = 144;
pub const CTRY_SWEDEN: ISOCountryCode = 752;
pub const CTRY_SWITZERLAND: ISOCountryCode = 756;
pub const CTRY_SYRIA: ISOCountryCode = 760;
pub const CTRY_TAIWAN: ISOCountryCode = 158;
pub const CTRY_THAILAND: ISOCountryCode = 764;
pub const CTRY_TRINIDAD_Y_TOBAGO: ISOCountryCode = 780;
pub const CTRY_TUNISIA: ISOCountryCode = 788;
pub const CTRY_TURKEY: ISOCountryCode = 792;
pub const CTRY_UAE: ISOCountryCode = 784;
pub const CTRY_UKRAINE: ISOCountryCode = 804;
pub const CTRY_UNITED_KINGDOM: ISOCountryCode = 826;
pub const CTRY_UNITED_STATES: ISOCountryCode = 840;
pub const CTRY_URUGUAY: ISOCountryCode = 858;
pub const CTRY_UZBEKISTAN: ISOCountryCode = 860;
pub const CTRY_VENEZUELA: ISOCountryCode = 862;
pub const CTRY_VIET_NAM: ISOCountryCode = 704;
pub const CTRY_YEMEN: ISOCountryCode = 887;
pub const CTRY_ZIMBABWE: ISOCountryCode = 716;
pub const CTRY_DEBUG: ISOCountryCode = 511;
pub const CTRY_DEFAULT: ISOCountryCode = 0;
pub const CTRY_UNITED_STATES_FCC49: ISOCountryCode = 842;
pub const CTRY_KOREA_ROC3: ISOCountryCode = 412;
pub const CTRY_JAPAN1: ISOCountryCode = 393;
pub const CTRY_JAPAN2: ISOCountryCode = 394;
pub const CTRY_JAPAN3: ISOCountryCode = 395;
pub const CTRY_JAPAN4: ISOCountryCode = 396;
pub const CTRY_JAPAN5: ISOCountryCode = 397;
pub const CTRY_JAPAN6: ISOCountryCode = 399;
pub const CTRY_JAPAN7: ISOCountryCode = 4007;
pub const CTRY_JAPAN8: ISOCountryCode = 4008;
pub const CTRY_JAPAN9: ISOCountryCode = 4009;
pub const CTRY_JAPAN10: ISOCountryCode = 4010;
pub const CTRY_JAPAN11: ISOCountryCode = 4011;
pub const CTRY_JAPAN12: ISOCountryCode = 4012;
pub const CTRY_JAPAN13: ISOCountryCode = 4013;
pub const CTRY_JAPAN14: ISOCountryCode = 4014;
pub const CTRY_JAPAN15: ISOCountryCode = 4015;
pub const CTRY_JAPAN16: ISOCountryCode = 4016;
pub const CTRY_JAPAN17: ISOCountryCode = 4017;
pub const CTRY_JAPAN18: ISOCountryCode = 4018;
pub const CTRY_JAPAN19: ISOCountryCode = 4019;
pub const CTRY_JAPAN20: ISOCountryCode = 4020;
pub const CTRY_JAPAN21: ISOCountryCode = 4021;
pub const CTRY_JAPAN22: ISOCountryCode = 4022;
pub const CTRY_JAPAN23: ISOCountryCode = 4023;
pub const CTRY_JAPAN24: ISOCountryCode = 4024;
pub type ISOCountryCode = ::core::ffi::c_uint;
pub const SKU_FCC: RegdomainCode = 16;
pub const SKU_CA: RegdomainCode = 32;
pub const SKU_ETSI: RegdomainCode = 48;
pub const SKU_ETSI2: RegdomainCode = 50;
pub const SKU_ETSI3: RegdomainCode = 51;
pub const SKU_FCC3: RegdomainCode = 58;
pub const SKU_JAPAN: RegdomainCode = 64;
pub const SKU_KOREA: RegdomainCode = 69;
pub const SKU_APAC: RegdomainCode = 80;
pub const SKU_APAC2: RegdomainCode = 81;
pub const SKU_APAC3: RegdomainCode = 93;
pub const SKU_ROW: RegdomainCode = 129;
pub const SKU_NONE: RegdomainCode = 240;
pub const SKU_DEBUG: RegdomainCode = 511;
pub const SKU_SR9: RegdomainCode = 664;
pub const SKU_XR9: RegdomainCode = 665;
pub const SKU_GZ901: RegdomainCode = 666;
pub const SKU_XC900M: RegdomainCode = 667;
pub type RegdomainCode = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct freqband {
    pub freqStart: u16,
    pub freqEnd: u16,
    pub chanWidth: u8,
    pub chanSep: u8,
    pub flags: u32,
    pub id: *const ::core::ffi::c_void,
    pub next: freqband__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct freqband__bindgen_ty_1 {
    pub le_next: *mut freqband,
    pub le_prev: *mut *mut freqband,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of freqband__bindgen_ty_1"]
        [::core::mem::size_of::<freqband__bindgen_ty_1>() - 16usize];
    ["Alignment of freqband__bindgen_ty_1"]
        [::core::mem::align_of::<freqband__bindgen_ty_1>() - 8usize];
    ["Offset of field: freqband__bindgen_ty_1::le_next"]
        [::core::mem::offset_of!(freqband__bindgen_ty_1, le_next) - 0usize];
    ["Offset of field: freqband__bindgen_ty_1::le_prev"]
        [::core::mem::offset_of!(freqband__bindgen_ty_1, le_prev) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of freqband"][::core::mem::size_of::<freqband>() - 40usize];
    ["Alignment of freqband"][::core::mem::align_of::<freqband>() - 8usize];
    ["Offset of field: freqband::freqStart"]
        [::core::mem::offset_of!(freqband, freqStart) - 0usize];
    ["Offset of field: freqband::freqEnd"]
        [::core::mem::offset_of!(freqband, freqEnd) - 2usize];
    ["Offset of field: freqband::chanWidth"]
        [::core::mem::offset_of!(freqband, chanWidth) - 4usize];
    ["Offset of field: freqband::chanSep"]
        [::core::mem::offset_of!(freqband, chanSep) - 5usize];
    ["Offset of field: freqband::flags"]
        [::core::mem::offset_of!(freqband, flags) - 8usize];
    ["Offset of field: freqband::id"]
        [::core::mem::offset_of!(freqband, id) - 16usize];
    ["Offset of field: freqband::next"]
        [::core::mem::offset_of!(freqband, next) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct netband {
    pub band: *const freqband,
    pub maxPower: u8,
    pub maxPowerDFS: u8,
    pub maxAntGain: u8,
    pub flags: u32,
    pub next: netband__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct netband__bindgen_ty_1 {
    pub le_next: *mut netband,
    pub le_prev: *mut *mut netband,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of netband__bindgen_ty_1"]
        [::core::mem::size_of::<netband__bindgen_ty_1>() - 16usize];
    ["Alignment of netband__bindgen_ty_1"]
        [::core::mem::align_of::<netband__bindgen_ty_1>() - 8usize];
    ["Offset of field: netband__bindgen_ty_1::le_next"]
        [::core::mem::offset_of!(netband__bindgen_ty_1, le_next) - 0usize];
    ["Offset of field: netband__bindgen_ty_1::le_prev"]
        [::core::mem::offset_of!(netband__bindgen_ty_1, le_prev) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of netband"][::core::mem::size_of::<netband>() - 32usize];
    ["Alignment of netband"][::core::mem::align_of::<netband>() - 8usize];
    ["Offset of field: netband::band"]
        [::core::mem::offset_of!(netband, band) - 0usize];
    ["Offset of field: netband::maxPower"]
        [::core::mem::offset_of!(netband, maxPower) - 8usize];
    ["Offset of field: netband::maxPowerDFS"]
        [::core::mem::offset_of!(netband, maxPowerDFS) - 9usize];
    ["Offset of field: netband::maxAntGain"]
        [::core::mem::offset_of!(netband, maxAntGain) - 10usize];
    ["Offset of field: netband::flags"]
        [::core::mem::offset_of!(netband, flags) - 12usize];
    ["Offset of field: netband::next"]
        [::core::mem::offset_of!(netband, next) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct netband_head {
    pub lh_first: *mut netband,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of netband_head"][::core::mem::size_of::<netband_head>() - 8usize];
    ["Alignment of netband_head"]
        [::core::mem::align_of::<netband_head>() - 8usize];
    ["Offset of field: netband_head::lh_first"]
        [::core::mem::offset_of!(netband_head, lh_first) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct regdomain {
    pub sku: RegdomainCode,
    pub name: *const ::core::ffi::c_char,
    pub cc: *const country,
    pub bands_11b: netband_head,
    pub bands_11g: netband_head,
    pub bands_11a: netband_head,
    pub bands_11ng: netband_head,
    pub bands_11na: netband_head,
    pub bands_11ac: netband_head,
    pub bands_11acg: netband_head,
    pub next: regdomain__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct regdomain__bindgen_ty_1 {
    pub le_next: *mut regdomain,
    pub le_prev: *mut *mut regdomain,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of regdomain__bindgen_ty_1"]
        [::core::mem::size_of::<regdomain__bindgen_ty_1>() - 16usize];
    ["Alignment of regdomain__bindgen_ty_1"]
        [::core::mem::align_of::<regdomain__bindgen_ty_1>() - 8usize];
    ["Offset of field: regdomain__bindgen_ty_1::le_next"]
        [::core::mem::offset_of!(regdomain__bindgen_ty_1, le_next) - 0usize];
    ["Offset of field: regdomain__bindgen_ty_1::le_prev"]
        [::core::mem::offset_of!(regdomain__bindgen_ty_1, le_prev) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of regdomain"][::core::mem::size_of::<regdomain>() - 96usize];
    ["Alignment of regdomain"][::core::mem::align_of::<regdomain>() - 8usize];
    ["Offset of field: regdomain::sku"]
        [::core::mem::offset_of!(regdomain, sku) - 0usize];
    ["Offset of field: regdomain::name"]
        [::core::mem::offset_of!(regdomain, name) - 8usize];
    ["Offset of field: regdomain::cc"]
        [::core::mem::offset_of!(regdomain, cc) - 16usize];
    ["Offset of field: regdomain::bands_11b"]
        [::core::mem::offset_of!(regdomain, bands_11b) - 24usize];
    ["Offset of field: regdomain::bands_11g"]
        [::core::mem::offset_of!(regdomain, bands_11g) - 32usize];
    ["Offset of field: regdomain::bands_11a"]
        [::core::mem::offset_of!(regdomain, bands_11a) - 40usize];
    ["Offset of field: regdomain::bands_11ng"]
        [::core::mem::offset_of!(regdomain, bands_11ng) - 48usize];
    ["Offset of field: regdomain::bands_11na"]
        [::core::mem::offset_of!(regdomain, bands_11na) - 56usize];
    ["Offset of field: regdomain::bands_11ac"]
        [::core::mem::offset_of!(regdomain, bands_11ac) - 64usize];
    ["Offset of field: regdomain::bands_11acg"]
        [::core::mem::offset_of!(regdomain, bands_11acg) - 72usize];
    ["Offset of field: regdomain::next"]
        [::core::mem::offset_of!(regdomain, next) - 80usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct country {
    pub code: ISOCountryCode,
    pub rd: *const regdomain,
    pub isoname: *const ::core::ffi::c_char,
    pub name: *const ::core::ffi::c_char,
    pub next: country__bindgen_ty_1,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct country__bindgen_ty_1 {
    pub le_next: *mut country,
    pub le_prev: *mut *mut country,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of country__bindgen_ty_1"]
        [::core::mem::size_of::<country__bindgen_ty_1>() - 16usize];
    ["Alignment of country__bindgen_ty_1"]
        [::core::mem::align_of::<country__bindgen_ty_1>() - 8usize];
    ["Offset of field: country__bindgen_ty_1::le_next"]
        [::core::mem::offset_of!(country__bindgen_ty_1, le_next) - 0usize];
    ["Offset of field: country__bindgen_ty_1::le_prev"]
        [::core::mem::offset_of!(country__bindgen_ty_1, le_prev) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of country"][::core::mem::size_of::<country>() - 48usize];
    ["Alignment of country"][::core::mem::align_of::<country>() - 8usize];
    ["Offset of field: country::code"]
        [::core::mem::offset_of!(country, code) - 0usize];
    ["Offset of field: country::rd"]
        [::core::mem::offset_of!(country, rd) - 8usize];
    ["Offset of field: country::isoname"]
        [::core::mem::offset_of!(country, isoname) - 16usize];
    ["Offset of field: country::name"]
        [::core::mem::offset_of!(country, name) - 24usize];
    ["Offset of field: country::next"]
        [::core::mem::offset_of!(country, next) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ident {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct regdata {
    pub countries: regdata__bindgen_ty_1,
    pub domains: regdata__bindgen_ty_2,
    pub freqbands: regdata__bindgen_ty_3,
    pub ident: *mut ident,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct regdata__bindgen_ty_1 {
    pub lh_first: *mut country,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of regdata__bindgen_ty_1"]
        [::core::mem::size_of::<regdata__bindgen_ty_1>() - 8usize];
    ["Alignment of regdata__bindgen_ty_1"]
        [::core::mem::align_of::<regdata__bindgen_ty_1>() - 8usize];
    ["Offset of field: regdata__bindgen_ty_1::lh_first"]
        [::core::mem::offset_of!(regdata__bindgen_ty_1, lh_first) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct regdata__bindgen_ty_2 {
    pub lh_first: *mut regdomain,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of regdata__bindgen_ty_2"]
        [::core::mem::size_of::<regdata__bindgen_ty_2>() - 8usize];
    ["Alignment of regdata__bindgen_ty_2"]
        [::core::mem::align_of::<regdata__bindgen_ty_2>() - 8usize];
    ["Offset of field: regdata__bindgen_ty_2::lh_first"]
        [::core::mem::offset_of!(regdata__bindgen_ty_2, lh_first) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct regdata__bindgen_ty_3 {
    pub lh_first: *mut freqband,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of regdata__bindgen_ty_3"]
        [::core::mem::size_of::<regdata__bindgen_ty_3>() - 8usize];
    ["Alignment of regdata__bindgen_ty_3"]
        [::core::mem::align_of::<regdata__bindgen_ty_3>() - 8usize];
    ["Offset of field: regdata__bindgen_ty_3::lh_first"]
        [::core::mem::offset_of!(regdata__bindgen_ty_3, lh_first) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of regdata"][::core::mem::size_of::<regdata>() - 32usize];
    ["Alignment of regdata"][::core::mem::align_of::<regdata>() - 8usize];
    ["Offset of field: regdata::countries"]
        [::core::mem::offset_of!(regdata, countries) - 0usize];
    ["Offset of field: regdata::domains"]
        [::core::mem::offset_of!(regdata, domains) - 8usize];
    ["Offset of field: regdata::freqbands"]
        [::core::mem::offset_of!(regdata, freqbands) - 16usize];
    ["Offset of field: regdata::ident"]
        [::core::mem::offset_of!(regdata, ident) - 24usize];
};
unsafe extern "C" {
    pub fn lib80211_alloc_regdata() -> *mut regdata;
}
unsafe extern "C" {
    pub fn lib80211_regdomain_findbysku(
        arg1: *const regdata,
        arg2: RegdomainCode,
    ) -> *const regdomain;
}
unsafe extern "C" {
    pub fn lib80211_regdomain_findbyname(
        arg1: *const regdata,
        arg2: *const ::core::ffi::c_char,
    ) -> *const regdomain;
}
unsafe extern "C" {
    pub fn lib80211_country_findbycc(
        arg1: *const regdata,
        arg2: ISOCountryCode,
    ) -> *const country;
}
unsafe extern "C" {
    pub fn lib80211_country_findbyname(
        arg1: *const regdata,
        arg2: *const ::core::ffi::c_char,
    ) -> *const country;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nd_ifinfo {
    pub linkmtu: u_int32_t,
    pub maxmtu: u_int32_t,
    pub basereachable: u_int32_t,
    pub reachable: u_int32_t,
    pub retrans: u_int32_t,
    pub flags: u_int32_t,
    pub recalctm: ::core::ffi::c_int,
    pub chlim: u_int8_t,
    pub initialized: u_int8_t,
    pub randomseed0: [u_int8_t; 8usize],
    pub randomseed1: [u_int8_t; 8usize],
    pub randomid: [u_int8_t; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nd_ifinfo"][::core::mem::size_of::<nd_ifinfo>() - 56usize];
    ["Alignment of nd_ifinfo"][::core::mem::align_of::<nd_ifinfo>() - 4usize];
    ["Offset of field: nd_ifinfo::linkmtu"]
        [::core::mem::offset_of!(nd_ifinfo, linkmtu) - 0usize];
    ["Offset of field: nd_ifinfo::maxmtu"]
        [::core::mem::offset_of!(nd_ifinfo, maxmtu) - 4usize];
    ["Offset of field: nd_ifinfo::basereachable"]
        [::core::mem::offset_of!(nd_ifinfo, basereachable) - 8usize];
    ["Offset of field: nd_ifinfo::reachable"]
        [::core::mem::offset_of!(nd_ifinfo, reachable) - 12usize];
    ["Offset of field: nd_ifinfo::retrans"]
        [::core::mem::offset_of!(nd_ifinfo, retrans) - 16usize];
    ["Offset of field: nd_ifinfo::flags"]
        [::core::mem::offset_of!(nd_ifinfo, flags) - 20usize];
    ["Offset of field: nd_ifinfo::recalctm"]
        [::core::mem::offset_of!(nd_ifinfo, recalctm) - 24usize];
    ["Offset of field: nd_ifinfo::chlim"]
        [::core::mem::offset_of!(nd_ifinfo, chlim) - 28usize];
    ["Offset of field: nd_ifinfo::initialized"]
        [::core::mem::offset_of!(nd_ifinfo, initialized) - 29usize];
    ["Offset of field: nd_ifinfo::randomseed0"]
        [::core::mem::offset_of!(nd_ifinfo, randomseed0) - 30usize];
    ["Offset of field: nd_ifinfo::randomseed1"]
        [::core::mem::offset_of!(nd_ifinfo, randomseed1) - 38usize];
    ["Offset of field: nd_ifinfo::randomid"]
        [::core::mem::offset_of!(nd_ifinfo, randomid) - 46usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct in6_ndireq {
    pub ifname: [::core::ffi::c_char; 16usize],
    pub ndi: nd_ifinfo,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of in6_ndireq"][::core::mem::size_of::<in6_ndireq>() - 72usize];
    ["Alignment of in6_ndireq"][::core::mem::align_of::<in6_ndireq>() - 4usize];
    ["Offset of field: in6_ndireq::ifname"]
        [::core::mem::offset_of!(in6_ndireq, ifname) - 0usize];
    ["Offset of field: in6_ndireq::ndi"]
        [::core::mem::offset_of!(in6_ndireq, ndi) - 16usize];
};
